import { Product } from '../types';

export const MOCK_PRODUCTS: Product[] = [
  {
    id: '1',
    name: 'Air Max 270 React',
    description: 'Nike\'s Air Max 270 React combines two groundbreaking Nike innovations to create a shoe that\'s designed for the everyday runner. The Nike Air Max 270 React features a large Max Air unit in the heel for cushioning and Nike React foam for a smooth ride.',
    price: 150,
    originalPrice: 180,
    images: [
      'https://images.unsplash.com/photo-1542291026-7eec264c27ff?w=600',
      'https://images.unsplash.com/photo-1549298916-b41d501d3772?w=600',
      'https://images.unsplash.com/photo-1606107557195-0e29a4b5b4aa?w=600',
    ],
    category: 'Running',
    brand: 'Nike',
    sizes: ['7', '8', '9', '10', '11', '12'],
    colors: ['Black', 'White', 'Red', 'Blue'],
    rating: 4.5,
    reviewCount: 128,
    inStock: true,
    isNew: true,
    isFeatured: true,
    discount: 17,
  },
  {
    id: '2',
    name: 'UltraBoost 22',
    description: 'Made with a series of recycled materials, this upper features at least 50% recycled content. Push your limits with UltraBoost technology and feel the energy return with every stride.',
    price: 190,
    originalPrice: 200,
    images: [
      'https://images.unsplash.com/photo-1606107557195-0e29a4b5b4aa?w=600',
      'https://images.unsplash.com/photo-1608231387042-66d1773070a5?w=600',
    ],
    category: 'Running',
    brand: 'Adidas',
    sizes: ['7', '8', '9', '10', '11', '12'],
    colors: ['Black', 'White', 'Blue', 'Gray'],
    rating: 4.7,
    reviewCount: 89,
    inStock: true,
    isFeatured: true,
    discount: 5,
  },
  {
    id: '3',
    name: 'LeBron XX',
    description: 'Designed to help you play like the King himself. The LeBron XX features Zoom Air cushioning and a lightweight, durable upper for explosive performance on the court.',
    price: 200,
    images: [
      'https://images.unsplash.com/photo-1546519638-68e109498ffc?w=600',
      'https://images.unsplash.com/photo-1539185441755-769473a23570?w=600',
    ],
    category: 'Basketball',
    brand: 'Nike',
    sizes: ['8', '9', '10', '11', '12', '13'],
    colors: ['Black', 'Red', 'Gold', 'White'],
    rating: 4.8,
    reviewCount: 156,
    inStock: true,
    isNew: true,
    isFeatured: true,
  },
  {
    id: '4',
    name: 'Puma RS-X',
    description: 'The RS-X returns with bold colors and a chunky silhouette. Perfect for streetwear enthusiasts looking for comfort and style.',
    price: 110,
    originalPrice: 140,
    images: [
      'https://images.unsplash.com/photo-1608231387042-66d1773070a5?w=600',
    ],
    category: 'Running',
    brand: 'Puma',
    sizes: ['7', '8', '9', '10', '11'],
    colors: ['White', 'Black', 'Red', 'Green'],
    rating: 4.3,
    reviewCount: 67,
    inStock: true,
    discount: 21,
  },
  {
    id: '5',
    name: 'Under Armour Curry 10',
    description: 'Stephen Curry\'s signature shoe featuring UA Flow cushioning technology for ultimate court feel and responsiveness.',
    price: 160,
    images: [
      'https://images.unsplash.com/photo-1539185441755-769473a23570?w=600',
    ],
    category: 'Basketball',
    brand: 'Under Armour',
    sizes: ['8', '9', '10', '11', '12'],
    colors: ['White', 'Blue', 'Black'],
    rating: 4.6,
    reviewCount: 92,
    inStock: true,
    isNew: true,
  },
  {
    id: '6',
    name: 'Adidas Predator Edge',
    description: 'Control the game with Predator Edge football boots. Featuring Control Frame 2.0 and Facet Frame outsole for precision and power.',
    price: 220,
    originalPrice: 250,
    images: [
      'https://images.unsplash.com/photo-1511556532299-8f662fc26c06?w=600',
    ],
    category: 'Football',
    brand: 'Adidas',
    sizes: ['7', '8', '9', '10', '11'],
    colors: ['Black', 'Red', 'White'],
    rating: 4.7,
    reviewCount: 134,
    inStock: true,
    discount: 12,
  },
  {
    id: '7',
    name: 'Nike Court Vision Low',
    description: 'Inspired by basketball heritage, the Nike Court Vision Low brings classic style to your everyday look with a comfortable fit.',
    price: 75,
    images: [
      'https://images.unsplash.com/photo-1549298916-b41d501d3772?w=600',
    ],
    category: 'Basketball',
    brand: 'Nike',
    sizes: ['7', '8', '9', '10', '11', '12'],
    colors: ['White', 'Black', 'Blue'],
    rating: 4.2,
    reviewCount: 45,
    inStock: true,
  },
  {
    id: '8',
    name: 'Adidas Speedflow',
    description: 'Lightweight and fast. The Speedflow boots are designed for players who rely on speed to break through defenses.',
    price: 180,
    images: [
      'https://images.unsplash.com/photo-1511556532299-8f662fc26c06?w=600',
    ],
    category: 'Football',
    brand: 'Adidas',
    sizes: ['7', '8', '9', '10', '11'],
    colors: ['White', 'Red', 'Black', 'Blue'],
    rating: 4.6,
    reviewCount: 78,
    inStock: true,
    isNew: true,
  },
  {
    id: '9',
    name: 'Puma Future Z',
    description: 'FUZIONFIT+ compression at midfoot adaptive fit and superior lockdown. Dynamic Motion System outsole for freedom of movement.',
    price: 200,
    originalPrice: 230,
    images: [
      'https://images.unsplash.com/photo-1511556532299-8f662fc26c06?w=600',
    ],
    category: 'Football',
    brand: 'Puma',
    sizes: ['7', '8', '9', '10', '11'],
    colors: ['Yellow', 'Black', 'Blue'],
    rating: 4.5,
    reviewCount: 103,
    inStock: true,
    isFeatured: true,
    discount: 13,
  },
  {
    id: '10',
    name: 'Nike Metcon 8',
    description: 'The most versatile workout shoe. Updated with a Hyperlift plate and wider heel for improved stability during heavy lifts.',
    price: 150,
    images: [
      'https://images.unsplash.com/photo-1534438327276-14e5300c3a48?w=600',
    ],
    category: 'Gym',
    brand: 'Nike',
    sizes: ['7', '8', '9', '10', '11', '12'],
    colors: ['Black', 'White', 'Red', 'Gray'],
    rating: 4.8,
    reviewCount: 201,
    inStock: true,
    isFeatured: true,
  },
];